### ISSUE TITLE
Information geometry ?

### ISSUE THREAD

**Issue by MLdoesML** [neurreps/awesome-neural-geometry#3]
Hi, do you think it is a good idea to add some stuff on information geometry? The repository so far focuses on the geometry of neural representation or ways to handle the fact that the data can be on some manifold i.e geometric deep learning. However, information geometry would be talking about the fact that the parameters of the model would lie on a manifold. I can make a PR for this.

**Comment by sophiaas** [comment]
Information geometry would be a great addition. Thanks for getting us started there!
